[package]
name = "CSVSM"
version = "0.1.0"
authors = ["Michael Bednarek <mbednarek360@protonmail.com>"]
repository = "https://github.com/mbednarek360/CSVSM"
edition = "2018"

[dependencies]
colored = "*"
csv = "*"
rand = "*"
